"""empty message

Revision ID: dfe904d0862e
Revises: 5b087377adab
Create Date: 2023-01-07 14:39:31.373313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe904d0862e'
down_revision = '5b087377adab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('bot_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'bot_id')
    # ### end Alembic commands ###
